export type TwinActionManifestEntry = {
  key: string;
  platform: "linkedin" | "reddit" | "x" | "instagram";
  action: string;
  kind: "read" | "write";
  requestedSlots: Record<string, number>;
  variableSlots: boolean;
  toolName: string;
  // No matching server-registry action: runs only in local mode.
  localOnly?: true;
};

export const TWIN_ACTION_MANIFEST: TwinActionManifestEntry[] = [
  {
    key: "instagram/comment",
    platform: "instagram",
    action: "comment",
    kind: "write",
    requestedSlots: {
      comment: 1,
    },
    variableSlots: false,
    toolName: "instagram_comment",
  },
  {
    key: "instagram/comments",
    platform: "instagram",
    action: "comments",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "instagram_comments",
  },
  {
    key: "instagram/feed-engage",
    platform: "instagram",
    action: "feed-engage",
    kind: "write",
    requestedSlots: {
      like: 1,
    },
    variableSlots: false,
    toolName: "instagram_feed_engage",
  },
  {
    key: "instagram/saved",
    platform: "instagram",
    action: "saved",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "instagram_saved",
  },
  {
    key: "linkedin/activity",
    platform: "linkedin",
    action: "activity",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_activity",
  },
  {
    key: "linkedin/analytics",
    platform: "linkedin",
    action: "analytics",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_analytics",
  },
  {
    key: "linkedin/comment",
    platform: "linkedin",
    action: "comment",
    kind: "write",
    requestedSlots: {
      comment: 1,
    },
    variableSlots: false,
    toolName: "linkedin_comment",
  },
  {
    key: "linkedin/comment-reactors",
    platform: "linkedin",
    action: "comment-reactors",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_comment_reactors",
  },
  {
    key: "linkedin/comments",
    platform: "linkedin",
    action: "comments",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_comments",
  },
  {
    key: "linkedin/company",
    platform: "linkedin",
    action: "company",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_company",
  },
  {
    key: "linkedin/connect",
    platform: "linkedin",
    action: "connect",
    kind: "write",
    requestedSlots: {
      connect: 1,
    },
    variableSlots: false,
    toolName: "linkedin_connect",
  },
  {
    key: "linkedin/connection-status",
    platform: "linkedin",
    action: "connection-status",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_connection_status",
  },
  {
    key: "linkedin/connections",
    platform: "linkedin",
    action: "connections",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_connections",
  },
  {
    key: "linkedin/conversations",
    platform: "linkedin",
    action: "conversations",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_conversations",
  },
  // Intentionally local-only and omitted from the manifest: conversation-state
  // binds a recipient-scoped WAB lookup to local Voyager credentials. Exposing
  // it as a generic cloud action requires a separate remote response contract.
  {
    key: "linkedin/delete-comment",
    platform: "linkedin",
    action: "delete-comment",
    kind: "write",
    requestedSlots: {
      comment: 1,
    },
    variableSlots: false,
    toolName: "linkedin_delete_comment",
  },
  {
    key: "linkedin/delete-post",
    platform: "linkedin",
    action: "delete-post",
    kind: "write",
    requestedSlots: {
      post: 1,
    },
    variableSlots: false,
    toolName: "linkedin_delete_post",
  },
  {
    key: "linkedin/edit-comment",
    platform: "linkedin",
    action: "edit-comment",
    kind: "write",
    requestedSlots: {
      comment: 1,
    },
    variableSlots: false,
    toolName: "linkedin_edit_comment",
  },
  {
    key: "linkedin/edit-post",
    platform: "linkedin",
    action: "edit-post",
    kind: "write",
    requestedSlots: {
      post: 1,
    },
    variableSlots: false,
    toolName: "linkedin_edit_post",
  },
  {
    key: "linkedin/engage-commenters",
    platform: "linkedin",
    action: "engage-commenters",
    kind: "write",
    requestedSlots: {
      like: 25,
      comment: 25,
      connect: 25,
    },
    variableSlots: true,
    toolName: "linkedin_engage_commenters",
  },
  {
    key: "linkedin/enrich",
    platform: "linkedin",
    action: "enrich",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_enrich",
  },
  {
    key: "linkedin/enrich-engagers",
    platform: "linkedin",
    action: "enrich-engagers",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_enrich_engagers",
  },
  {
    key: "linkedin/feed-engage",
    platform: "linkedin",
    action: "feed-engage",
    kind: "write",
    requestedSlots: {
      like: 1,
    },
    variableSlots: false,
    toolName: "linkedin_feed_engage",
  },
  {
    key: "linkedin/follow",
    platform: "linkedin",
    action: "follow",
    kind: "write",
    requestedSlots: {
      follow: 1,
    },
    variableSlots: false,
    toolName: "linkedin_follow",
  },
  {
    key: "linkedin/inmail",
    platform: "linkedin",
    action: "inmail",
    kind: "write",
    requestedSlots: {
      inmail: 1,
    },
    variableSlots: false,
    toolName: "linkedin_inmail",
  },
  {
    key: "linkedin/inmail-credits",
    platform: "linkedin",
    action: "inmail-credits",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_inmail_credits",
  },
  {
    key: "linkedin/invitations",
    platform: "linkedin",
    action: "invitations",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_invitations",
  },
  {
    key: "linkedin/like",
    platform: "linkedin",
    action: "like",
    kind: "write",
    requestedSlots: {
      like: 1,
    },
    variableSlots: false,
    toolName: "linkedin_like",
  },
  {
    key: "linkedin/me",
    platform: "linkedin",
    action: "me",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_me",
  },
  {
    key: "linkedin/messages",
    platform: "linkedin",
    action: "messages",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_messages",
  },
  {
    key: "linkedin/mute",
    platform: "linkedin",
    action: "mute",
    kind: "write",
    requestedSlots: {
      mute: 1,
    },
    variableSlots: false,
    toolName: "linkedin_mute",
  },
  {
    key: "linkedin/notifications",
    platform: "linkedin",
    action: "notifications",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_notifications",
  },
  {
    key: "linkedin/post",
    platform: "linkedin",
    action: "post",
    kind: "write",
    requestedSlots: {
      post: 1,
    },
    variableSlots: false,
    toolName: "linkedin_post",
  },
  {
    key: "linkedin/post-details",
    platform: "linkedin",
    action: "post-details",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_post_details",
  },
  {
    key: "linkedin/posts",
    platform: "linkedin",
    action: "posts",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_posts",
  },
  {
    key: "linkedin/profile",
    platform: "linkedin",
    action: "profile",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_profile",
  },
  {
    key: "linkedin/reactions",
    platform: "linkedin",
    action: "reactions",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_reactions",
  },
  {
    key: "linkedin/reply-comment",
    platform: "linkedin",
    action: "reply-comment",
    kind: "write",
    requestedSlots: {
      comment: 1,
    },
    variableSlots: false,
    toolName: "linkedin_reply_comment",
  },
  {
    key: "linkedin/salesnav-alerts",
    platform: "linkedin",
    action: "salesnav-alerts",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_alerts",
  },
  {
    key: "linkedin/salesnav-facets",
    platform: "linkedin",
    action: "salesnav-facets",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_facets",
  },
  {
    key: "linkedin/salesnav-insights",
    platform: "linkedin",
    action: "salesnav-insights",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_insights",
  },
  {
    key: "linkedin/salesnav-lists",
    platform: "linkedin",
    action: "salesnav-lists",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_lists",
  },
  {
    key: "linkedin/salesnav-notifications",
    platform: "linkedin",
    action: "salesnav-notifications",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_notifications",
  },
  {
    key: "linkedin/salesnav-personas",
    platform: "linkedin",
    action: "salesnav-personas",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_personas",
  },
  {
    key: "linkedin/salesnav-profile",
    platform: "linkedin",
    action: "salesnav-profile",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_profile",
  },
  {
    key: "linkedin/salesnav-recent",
    platform: "linkedin",
    action: "salesnav-recent",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_recent",
  },
  {
    key: "linkedin/salesnav-recommended-companies",
    platform: "linkedin",
    action: "salesnav-recommended-companies",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_recommended_companies",
  },
  {
    key: "linkedin/salesnav-recommended-leads",
    platform: "linkedin",
    action: "salesnav-recommended-leads",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_recommended_leads",
  },
  {
    key: "linkedin/salesnav-saved-searches",
    platform: "linkedin",
    action: "salesnav-saved-searches",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_saved_searches",
  },
  {
    key: "linkedin/salesnav-search",
    platform: "linkedin",
    action: "salesnav-search",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_search",
  },
  {
    key: "linkedin/salesnav-spotlights",
    platform: "linkedin",
    action: "salesnav-spotlights",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_spotlights",
  },
  {
    key: "linkedin/salesnav-typeahead",
    platform: "linkedin",
    action: "salesnav-typeahead",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_typeahead",
  },
  {
    key: "linkedin/salesnav-warm-intro",
    platform: "linkedin",
    action: "salesnav-warm-intro",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_salesnav_warm_intro",
  },
  {
    key: "linkedin/salesnav-save-lead",
    platform: "linkedin",
    action: "salesnav-save-lead",
    kind: "write",
    requestedSlots: { "save-lead": 1 },
    variableSlots: false,
    toolName: "linkedin_salesnav_save_lead",
  },
  {
    key: "linkedin/salesnav-save-search",
    platform: "linkedin",
    action: "salesnav-save-search",
    kind: "write",
    requestedSlots: { "save-search": 1 },
    variableSlots: false,
    toolName: "linkedin_salesnav_save_search",
  },
  {
    key: "linkedin/salesnav-delete-saved-search",
    platform: "linkedin",
    action: "salesnav-delete-saved-search",
    kind: "write",
    requestedSlots: { "delete-saved-search": 1 },
    variableSlots: false,
    toolName: "linkedin_salesnav_delete_saved_search",
  },
  {
    key: "linkedin/salesnav-create-list",
    platform: "linkedin",
    action: "salesnav-create-list",
    kind: "write",
    requestedSlots: { "create-list": 1 },
    variableSlots: false,
    toolName: "linkedin_salesnav_create_list",
  },
  {
    key: "linkedin/salesnav-delete-list",
    platform: "linkedin",
    action: "salesnav-delete-list",
    kind: "write",
    requestedSlots: { "delete-list": 1 },
    variableSlots: false,
    toolName: "linkedin_salesnav_delete_list",
  },
  {
    key: "linkedin/salesnav-list-add",
    platform: "linkedin",
    action: "salesnav-list-add",
    kind: "write",
    requestedSlots: { "list-add": 1 },
    variableSlots: false,
    toolName: "linkedin_salesnav_list_add",
  },
  {
    key: "linkedin/salesnav-list-remove",
    platform: "linkedin",
    action: "salesnav-list-remove",
    kind: "write",
    requestedSlots: { "list-remove": 1 },
    variableSlots: false,
    toolName: "linkedin_salesnav_list_remove",
  },
  {
    key: "linkedin/salesnav-message",
    platform: "linkedin",
    action: "salesnav-message",
    kind: "write",
    requestedSlots: { message: 1 },
    variableSlots: false,
    toolName: "linkedin_salesnav_message",
  },
  {
    key: "linkedin/salesnav-connect",
    platform: "linkedin",
    action: "salesnav-connect",
    kind: "write",
    // Preview-first (mirrors the hosted registry): the default send:false
    // call consumes NO slot; send:true charges exactly {connect:1}.
    requestedSlots: { connect: 1 },
    variableSlots: true,
    toolName: "linkedin_salesnav_connect",
  },
  {
    key: "linkedin/saves",
    platform: "linkedin",
    action: "saves",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_saves",
  },
  {
    key: "linkedin/search",
    platform: "linkedin",
    action: "search",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_search",
  },
  {
    key: "linkedin/search-posts",
    platform: "linkedin",
    action: "search-posts",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_search_posts",
  },
  {
    key: "linkedin/send-message",
    platform: "linkedin",
    action: "send-message",
    kind: "write",
    requestedSlots: {
      message: 1,
    },
    variableSlots: false,
    toolName: "linkedin_send_message",
  },
  {
    key: "linkedin/sent-invitations",
    platform: "linkedin",
    action: "sent-invitations",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "linkedin_sent_invitations",
  },
  {
    key: "linkedin/unlike",
    platform: "linkedin",
    action: "unlike",
    kind: "write",
    requestedSlots: {
      like: 1,
    },
    variableSlots: false,
    toolName: "linkedin_unlike",
  },
  {
    key: "linkedin/visit",
    platform: "linkedin",
    action: "visit",
    kind: "write",
    requestedSlots: {
      visit: 1,
    },
    variableSlots: false,
    toolName: "linkedin_visit",
  },
  {
    key: "reddit/analytics",
    platform: "reddit",
    action: "analytics",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_analytics",
  },
  {
    key: "reddit/chat-accept",
    platform: "reddit",
    action: "chat-accept",
    kind: "write",
    requestedSlots: {
      message: 1,
    },
    variableSlots: false,
    toolName: "reddit_chat_accept",
  },
  {
    key: "reddit/chat-accept-all",
    platform: "reddit",
    action: "chat-accept-all",
    kind: "write",
    requestedSlots: {
      message: 1,
    },
    variableSlots: false,
    toolName: "reddit_chat_accept_all",
  },
  {
    key: "reddit/chat-inbox",
    platform: "reddit",
    action: "chat-inbox",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_chat_inbox",
  },
  {
    key: "reddit/chat-messages",
    platform: "reddit",
    action: "chat-messages",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_chat_messages",
  },
  {
    key: "reddit/chat-send",
    platform: "reddit",
    action: "chat-send",
    kind: "write",
    requestedSlots: {
      message: 1,
    },
    variableSlots: false,
    toolName: "reddit_chat_send",
  },
  {
    key: "reddit/chat-start",
    platform: "reddit",
    action: "chat-start",
    kind: "write",
    requestedSlots: {
      message: 1,
    },
    variableSlots: false,
    toolName: "reddit_chat_start",
  },
  {
    key: "reddit/comment",
    platform: "reddit",
    action: "comment",
    kind: "write",
    requestedSlots: {
      comment: 1,
    },
    variableSlots: false,
    toolName: "reddit_comment",
  },
  {
    key: "reddit/comments",
    platform: "reddit",
    action: "comments",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_comments",
  },
  {
    key: "reddit/delete",
    platform: "reddit",
    action: "delete",
    kind: "write",
    requestedSlots: {
      delete: 1,
    },
    variableSlots: false,
    toolName: "reddit_delete",
  },
  {
    key: "reddit/feed",
    platform: "reddit",
    action: "feed",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_feed",
  },
  {
    key: "reddit/feed-engage",
    platform: "reddit",
    action: "feed-engage",
    kind: "write",
    requestedSlots: {
      vote: 1,
    },
    variableSlots: false,
    toolName: "reddit_feed_engage",
  },
  {
    key: "reddit/home",
    platform: "reddit",
    action: "home",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_home",
  },
  {
    key: "reddit/inbox",
    platform: "reddit",
    action: "inbox",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_inbox",
  },
  {
    key: "reddit/post",
    platform: "reddit",
    action: "post",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_post",
  },
  {
    key: "reddit/rules",
    platform: "reddit",
    action: "rules",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_rules",
  },
  {
    key: "reddit/save",
    platform: "reddit",
    action: "save",
    kind: "write",
    requestedSlots: {
      save: 1,
    },
    variableSlots: false,
    toolName: "reddit_save",
  },
  {
    key: "reddit/saved",
    platform: "reddit",
    action: "saved",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_saved",
  },
  {
    key: "reddit/search",
    platform: "reddit",
    action: "search",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_search",
  },
  {
    key: "reddit/submit",
    platform: "reddit",
    action: "submit",
    kind: "write",
    requestedSlots: {
      submit: 1,
    },
    variableSlots: false,
    toolName: "reddit_submit",
  },
  {
    key: "reddit/subreddit",
    platform: "reddit",
    action: "subreddit",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_subreddit",
  },
  {
    key: "reddit/subscribe",
    platform: "reddit",
    action: "subscribe",
    kind: "write",
    requestedSlots: {
      subscribe: 1,
    },
    variableSlots: false,
    toolName: "reddit_subscribe",
  },
  {
    key: "reddit/trending",
    platform: "reddit",
    action: "trending",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_trending",
  },
  {
    key: "reddit/unsave",
    platform: "reddit",
    action: "unsave",
    kind: "write",
    requestedSlots: {
      save: 1,
    },
    variableSlots: false,
    toolName: "reddit_unsave",
  },
  {
    key: "reddit/user",
    platform: "reddit",
    action: "user",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_user",
  },
  {
    key: "reddit/user-comments",
    platform: "reddit",
    action: "user-comments",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_user_comments",
  },
  {
    key: "reddit/user-posts",
    platform: "reddit",
    action: "user-posts",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_user_posts",
  },
  {
    key: "reddit/vote",
    platform: "reddit",
    action: "vote",
    kind: "write",
    requestedSlots: {
      vote: 1,
    },
    variableSlots: false,
    toolName: "reddit_vote",
  },
  {
    key: "reddit/whoami",
    platform: "reddit",
    action: "whoami",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "reddit_whoami",
  },
  {
    key: "x/analytics",
    platform: "x",
    action: "analytics",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_analytics",
  },
  {
    key: "x/bookmark",
    platform: "x",
    action: "bookmark",
    kind: "write",
    requestedSlots: {
      bookmark: 1,
    },
    variableSlots: false,
    toolName: "x_bookmark",
  },
  {
    key: "x/bookmarks",
    platform: "x",
    action: "bookmarks",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_bookmarks",
  },
  {
    key: "x/delete",
    platform: "x",
    action: "delete",
    kind: "write",
    requestedSlots: {
      delete: 1,
    },
    variableSlots: false,
    toolName: "x_delete",
  },
  {
    key: "x/dm-accept",
    platform: "x",
    action: "dm-accept",
    kind: "write",
    requestedSlots: {
      message: 1,
    },
    variableSlots: false,
    toolName: "x_dm_accept",
    localOnly: true,
  },
  {
    key: "x/dm-inbox",
    platform: "x",
    action: "dm-inbox",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_dm_inbox",
    localOnly: true,
  },
  {
    key: "x/dm-read",
    platform: "x",
    action: "dm-read",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_dm_read",
    localOnly: true,
  },
  {
    key: "x/dm-requests",
    platform: "x",
    action: "dm-requests",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_dm_requests",
    localOnly: true,
  },
  {
    key: "x/dm-send",
    platform: "x",
    action: "dm-send",
    kind: "write",
    requestedSlots: {
      message: 1,
    },
    variableSlots: false,
    toolName: "x_dm_send",
    localOnly: true,
  },
  {
    key: "x/dm-start",
    platform: "x",
    action: "dm-start",
    kind: "write",
    requestedSlots: {
      message: 1,
    },
    variableSlots: false,
    toolName: "x_dm_start",
    localOnly: true,
  },
  {
    key: "x/feed-engage",
    platform: "x",
    action: "feed-engage",
    kind: "write",
    requestedSlots: {
      like: 1,
    },
    variableSlots: false,
    toolName: "x_feed_engage",
  },
  {
    key: "x/follow",
    platform: "x",
    action: "follow",
    kind: "write",
    requestedSlots: {
      follow: 1,
    },
    variableSlots: false,
    toolName: "x_follow",
  },
  {
    key: "x/followers",
    platform: "x",
    action: "followers",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_followers",
  },
  {
    key: "x/following",
    platform: "x",
    action: "following",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_following",
  },
  {
    key: "x/home",
    platform: "x",
    action: "home",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_home",
  },
  {
    key: "x/like",
    platform: "x",
    action: "like",
    kind: "write",
    requestedSlots: {
      like: 1,
    },
    variableSlots: false,
    toolName: "x_like",
  },
  {
    key: "x/likes",
    platform: "x",
    action: "likes",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_likes",
  },
  {
    key: "x/list-timeline",
    platform: "x",
    action: "list-timeline",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_list_timeline",
  },
  {
    key: "x/lists",
    platform: "x",
    action: "lists",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_lists",
  },
  {
    key: "x/mentions",
    platform: "x",
    action: "mentions",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_mentions",
  },
  {
    key: "x/news",
    platform: "x",
    action: "news",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_news",
  },
  {
    key: "x/quote",
    platform: "x",
    action: "quote",
    kind: "write",
    requestedSlots: {
      quote: 1,
    },
    variableSlots: false,
    toolName: "x_quote",
  },
  {
    key: "x/read",
    platform: "x",
    action: "read",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_read",
  },
  {
    key: "x/replies",
    platform: "x",
    action: "replies",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_replies",
  },
  {
    key: "x/reply",
    platform: "x",
    action: "reply",
    kind: "write",
    requestedSlots: {
      reply: 1,
    },
    variableSlots: false,
    toolName: "x_reply",
  },
  {
    key: "x/retweet",
    platform: "x",
    action: "retweet",
    kind: "write",
    requestedSlots: {
      retweet: 1,
    },
    variableSlots: false,
    toolName: "x_retweet",
  },
  {
    key: "x/search",
    platform: "x",
    action: "search",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_search",
  },
  {
    key: "x/thread",
    platform: "x",
    action: "thread",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_thread",
  },
  {
    key: "x/tweet",
    platform: "x",
    action: "tweet",
    kind: "write",
    requestedSlots: {
      tweet: 1,
    },
    variableSlots: false,
    toolName: "x_tweet",
  },
  {
    key: "x/unbookmark",
    platform: "x",
    action: "unbookmark",
    kind: "write",
    requestedSlots: {
      bookmark: 1,
    },
    variableSlots: false,
    toolName: "x_unbookmark",
  },
  {
    key: "x/unfollow",
    platform: "x",
    action: "unfollow",
    kind: "write",
    requestedSlots: {
      follow: 1,
    },
    variableSlots: false,
    toolName: "x_unfollow",
  },
  {
    key: "x/unlike",
    platform: "x",
    action: "unlike",
    kind: "write",
    requestedSlots: {
      like: 1,
    },
    variableSlots: false,
    toolName: "x_unlike",
  },
  {
    key: "x/unretweet",
    platform: "x",
    action: "unretweet",
    kind: "write",
    requestedSlots: {
      retweet: 1,
    },
    variableSlots: false,
    toolName: "x_unretweet",
  },
  {
    key: "x/user",
    platform: "x",
    action: "user",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_user",
  },
  {
    key: "x/user-tweets",
    platform: "x",
    action: "user-tweets",
    kind: "read",
    requestedSlots: {},
    variableSlots: false,
    toolName: "x_user_tweets",
  },
];
